# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4faa3ae633f0a42b6fa158243087cc7522c560b8bfbf11aafe3e2dbe5140d2799a032243489b3db37a1454d1c66933262193149c11a4ca27528025e3313d7c34

test:
  secret_key_base: 57357ee19310b6c24aa183083e12930733323e9dae3b95b202ea019e400ccce417267f7ea903102fc9b9cce47e6de7583b5bac029359419014dd6998c0ddbe73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
